### ISSUE TITLE
QR codes generated are wrong

### ISSUE THREAD

**Issue by errolt** [token2/Migration-Toolset#3]
The script successfully parses the image with 3 accounts, and creates the html file with 3 QR codes.

But all the QR codes are the same, and contains the data of the original QR code that was parsed.

The original QR code contained this:
'otpauth-migration://offline?data=ChsKDQAAAAAAAAAAAAAAAAASBHRlc3QgASgBMAIKGgoLCEIQhCEIQhCEIQgSBXRlc3QyIAEoATACChoKCxCEIQhCEIQhCEIQEgV0ZXN0MyABKAEwAhABGAEgACi4j%2FjZ%2F%2F%2F%2F%2F%2F8B'

All the QR codes on the generated html page contain the same:
'otpauth-migration://offline?data=ChsKDQAAAAAAAAAAAAAAAAASBHRlc3QgASgBMAIKGgoLCEIQhCEIQhCEIQgSBXRlc3QyIAEoATACChoKCxCEIQhCEIQhCEIQEgV0ZXN0MyABKAEwAhABGAEgACi4j%2FjZ%2F%2F%2F%2F%2F%2F8B'

Instead of the expected QR content of:
otpauth://totp/test?secret=AAAAAAAAAAAAAAAAAAAAA
otpauth://totp/test2?secret=BBBBBBBBBBBBBBBBBA
otpauth://totp/test3?secret=CCCCCCCCCCCCCCCCCA

Looking at the code, when the html file is saved, a generic "+qr_as_image_base64+" is saved for each image, which never changes, and was generated at the start of the program.

**Comment by token2** [comment]
Thanks for reporting, we will look at it

**Comment by errolt** [comment]
Adding

                from qrcode import QRCode
                import qrcode.image.svg
                from io import BytesIO
                qr = QRCode()
                qr.add_data(keyURI)
                img = qr.make_image(fill_color='black', back_color='white',image_factory=qrcode.image.svg.SvgImage)
                buffered = BytesIO()
                img.save(buffered)
                qr_as_image_base64 = base64.b64encode(buffered.getvalue())
                qr_as_image_base64=qr_as_image_base64.decode('utf-8')


before
`                f2.write('TOTP Profile '+str(line_count+j)+':'+otp.name +
                         "<br><img width=250 src='data:image/svg+xml;base64;utf-8,"+qr_as_image_base64+"'><pre>"+secret+"</pre><hr><br><br>")
`
fixes the issue. But it might not be the cleanest option.

**Comment by token2support** [comment]
> The script successfully parses the image with 3 accounts, and creates the html file with 3 QR codes.
> 
> But all the QR codes are the same, and contains the data of the original QR code that was parsed.
> 
> The original QR code contained this: 'otpauth-migration://offline?data=ChsKDQAAAAAAAAAAAAAAAAASBHRlc3QgASgBMAIKGgoLCEIQhCEIQhCEIQgSBXRlc3QyIAEoATACChoKCxCEIQhCEIQhCEIQEgV0ZXN0MyABKAEwAhABGAEgACi4j%2FjZ%2F%2F%2F%2F%2F%2F8B'
> 
> All the QR codes on the generated html page contain the same: 'otpauth-migration://offline?data=ChsKDQAAAAAAAAAAAAAAAAASBHRlc3QgASgBMAIKGgoLCEIQhCEIQhCEIQgSBXRlc3QyIAEoATACChoKCxCEIQhCEIQhCEIQEgV0ZXN0MyABKAEwAhABGAEgACi4j%2FjZ%2F%2F%2F%2F%2F%2F8B'
> 
> Instead of the expected QR content of: otpauth://totp/test?secret=AAAAAAAAAAAAAAAAAAAAA otpauth://totp/test2?secret=BBBBBBBBBBBBBBBBBA otpauth://totp/test3?secret=CCCCCCCCCCCCCCCCCA
> 
> Looking at the code, when the html file is saved, a generic "+qr_as_image_base64+" is saved for each image, which never changes, and was generated at the start of the program.

Hello. We were able to see this issue as you reported. Also special thanks for the solution. Your solution works.
